export const katakanaDummyData = [

      { japanese: "ア", english: "a" },
      { japanese: "イ", english: "i" },
      { japanese: "ウ", english: "u" },
      { japanese: "エ", english: "e" },
      { japanese: "オ", english: "o" },
      { japanese: "カ", english: "ka" }, 
      { japanese: "キ", english: "ki" },
      { japanese: "ク", english: "ku" },
      { japanese: "ケ", english: "ke" },
      { japanese: "コ", english: "ko" },
      { japanese: "サ", english: "sa" }, 
      { japanese: "シ", english: "shi" },
      { japanese: "ス", english: "su" },
      { japanese: "セ", english: "se" },
      { japanese: "ソ", english: "so" },

      { japanese: "タ", english: "ta" }, 
      { japanese: "チ", english: "chi" },
      { japanese: "ツ", english: "tsu" },
      { japanese: "テ", english: "te" },
      { japanese: "ト", english: "to" },

      { japanese: "ナ", english: "na" }, 
      { japanese: "ニ", english: "ni" },
      { japanese: "ヌ", english: "nu" },
      { japanese: "ネ", english: "ne" },
      { japanese: "ノ", english: "no" },
 
      { japanese: "ハ", english: "ha" }, 
      { japanese: "ヒ", english: "hi" },
      { japanese: "フ", english: "fu" },
      { japanese: "ヘ", english: "he" },
      { japanese: "ホ", english: "ho" },

      { japanese: "マ", english: "ma" }, 
      { japanese: "ミ", english: "mi" },
      { japanese: "ム", english: "mu" },
      { japanese: "メ", english: "me" },
      { japanese: "モ", english: "mo" },

      { japanese: "ヤ", english: "ya" }, 
      { japanese: "ユ", english: "yu" },
      { japanese: "ヨ", english: "yo" },

      { japanese: "ラ", english: "ra" }, 
      { japanese: "リ", english: "ri" },
      { japanese: "ル", english: "ru" },
      { japanese: "レ", english: "re" },
      { japanese: "ロ", english: "ro" },

      { japanese: "ワ", english: "wa" }, 
      { japanese: "ヲ", english: "wo" },
      { japanese: "ン", english: "n" },

      { japanese: "ガ", english: "ga" }, 
      { japanese: "ギ", english: "gi" },
      { japanese: "グ", english: "gu" },
      { japanese: "ゲ", english: "ge" },
      { japanese: "ゴ", english: "go" },
      { japanese: "ザ", english: "za" }, 
      { japanese: "ジ", english: "ji" },
      { japanese: "ズ", english: "zu" },
      { japanese: "ゼ", english: "ze" },
      { japanese: "ゾ", english: "zo" },

      { japanese: "ダ", english: "da" }, 
      { japanese: "ヂ", english: "dji" },
      { japanese: "ヅ", english: "dzu" },
      { japanese: "デ", english: "de" },
      { japanese: "ド", english: "do" },

      { japanese: "バ", english: "ba" }, 
      { japanese: "ビ", english: "bi" },
      { japanese: "ブ", english: "bu" },
      { japanese: "ベ", english: "be" },
      { japanese: "ボ", english: "bo" },
  
      { japanese: "パ", english: "pa" }, 
      { japanese: "ピ", english: "pi" },
      { japanese: "プ", english: "pu" },
      { japanese: "ペ", english: "pe" },
      { japanese: "ポ", english: "po" },
]
